from zhihu import User, UserDetail, Question
user = UserDetail("https://www.zhihu.com/people/lan-jiang-26")
t = user.get_followees()
user.get_followees_num()
# print(user.get_user_id())
print(user.get_data_id())
print(user.get_gender())
print(user.get_followees_num())
print(user.get_followers_num())
print(user.get_agree_num())
print(user.get_thanks_num())
print(user.get_asks_num())
print(user.get_answers_num())
print(user.get_collections_num())
print(user.get_profile_vote_num())
print(user.get_profile_thank_num())
print(user.get_profile_fav_num())
print(user.get_followers())
for user in user.get_followers():
    print(user)
t = user.get_topics()
question = Question(url='https://www.zhihu.com/question/32046716')
print(question.get_detail())
print(question.get_title ())

